# Generated by Django 3.0.5 on 2020-08-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
