# Generated by Django 3.0.5 on 2020-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(),
        ),
    ]
