# Generated by Django 3.0.5 on 2020-08-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0005_auto_20200820_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.Customer', verbose_name='Client'),
        ),
    ]
