# Generated by Django 3.0.5 on 2020-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0009_auto_20200820_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(verbose_name='Montant total (EUR)'),
        ),
    ]
