# Generated by Django 3.0.5 on 2020-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0011_auto_20200824_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name="Nombre d'articles"),
        ),
    ]
