# Generated by Django 3.0.5 on 2020-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0012_auto_20200824_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_amount',
            field=models.FloatField(null=True, verbose_name='Montant de ligne (EUR)'),
        ),
    ]
