# Generated by Django 3.0.5 on 2020-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0013_auto_20200824_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Nombre d'articles"),
        ),
    ]
