# Generated by Django 3.0.5 on 2020-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0014_auto_20200824_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name="Nombre d'articles"),
        ),
    ]
