# Generated by Django 3.0.5 on 2020-08-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0015_auto_20200824_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_number',
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60, verbose_name='Ville')),
                ('street', models.CharField(max_length=60, verbose_name='Rue')),
                ('street_number', models.CharField(max_length=60, verbose_name='Numéro')),
                ('postal_code', models.CharField(max_length=60, verbose_name='Code postal')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moon.Customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moon.Order')),
            ],
            options={
                'verbose_name': 'Adresse livraison',
                'verbose_name_plural': 'Adresses livraison',
            },
        ),
    ]
