# Generated by Django 3.0.5 on 2020-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0017_auto_20200825_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
