# Generated by Django 3.0.5 on 2020-08-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0018_auto_20200827_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mail',
            new_name='email',
        ),
    ]
