# Generated by Django 3.0.5 on 2020-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0019_auto_20200827_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email'),
        ),
    ]
