# Generated by Django 3.0.5 on 2020-09-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0020_auto_20200831_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moon.Product', verbose_name='Produit'),
        ),
    ]
