# Generated by Django 3.0.5 on 2020-09-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0022_auto_20200908_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
