# Generated by Django 3.0.5 on 2020-09-09 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moon', '0024_auto_20200909_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favourite',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField(default=False, verbose_name='is_favourite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moon.Product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourites',
            },
        ),
    ]
