# Generated by Django 3.0.5 on 2020-09-09 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moon', '0025_auto_20200909_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='is_liked',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='is_liked'),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
