# Generated by Django 3.0.5 on 2020-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0026_auto_20200909_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_liked',
            field=models.CharField(default='false', max_length=60, verbose_name='is_liked'),
        ),
    ]
