# Generated by Django 3.0.5 on 2020-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0028_auto_20200909_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name="Nombre d'articles"),
        ),
    ]
