# Generated by Django 3.0.5 on 2020-09-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0029_auto_20200910_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='discount',
            new_name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.Product'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.Discount'),
        ),
    ]
