# Generated by Django 3.0.5 on 2020-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0030_auto_20200916_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='promo',
            new_name='discount',
        ),
    ]
