# Generated by Django 3.0.5 on 2020-09-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0031_auto_20200916_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discount',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.ManyToManyField(blank=True, related_name='discount', to='moon.Discount'),
        ),
    ]
