# Generated by Django 3.0.5 on 2020-09-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0033_discount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='is_liked'),
        ),
    ]
