# Generated by Django 3.0.5 on 2020-09-17 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moon', '0034_product_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discounted',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_User',
            field=models.ManyToManyField(blank=True, related_name='users_pour_qui_soldé', to=settings.AUTH_USER_MODEL),
        ),
    ]
