# Generated by Django 3.0.5 on 2020-09-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0035_auto_20200917_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_User',
            new_name='discountUser',
        ),
    ]
