# Generated by Django 3.0.5 on 2020-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0038_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='coupon'),
        ),
    ]
