# Generated by Django 3.0.5 on 2020-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0041_itemvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('size', 'size'), ('color', 'color')], default='size', max_length=50),
        ),
    ]
