# Generated by Django 3.0.5 on 2020-10-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0042_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moon.Product', verbose_name='Produit'),
        ),
    ]
