# Generated by Django 3.0.5 on 2020-10-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0043_auto_20201017_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.Product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='size', max_length=50),
        ),
    ]
