# Generated by Django 3.0.5 on 2020-10-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0046_auto_20201017_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='shoes',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('package', 'package'), ('size', 'size')], default='size', max_length=50),
        ),
    ]
