# Generated by Django 3.0.5 on 2020-10-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0049_auto_20201017_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.ProductType'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('package', 'package'), ('size', 'size')], default='size', max_length=50),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
