# Generated by Django 3.0.5 on 2020-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0053_auto_20201018_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='been_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=50),
        ),
    ]
