# Generated by Django 3.0.5 on 2020-10-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0054_auto_20201018_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flag_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
