# Generated by Django 3.0.5 on 2020-10-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0055_userprofile_flag_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
