# Generated by Django 3.0.5 on 2020-10-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0057_auto_20201019_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant total (EUR)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre d'articles"),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('color', 'color'), ('size', 'size')], default='size', max_length=50),
        ),
    ]
